curRow  equ 0D00595h
penCol  equ 0D008D2h
curPC   equ 0D0231Ah
endPC   equ 0D0231Dh

_VPutS          equ 0020834h
_VPutMap        equ 0020830h
_Mov9ToOP1      equ 0020320h
_ChkFindSym     equ 002050Ch
_CreateAppVar   equ 0021330h
_Arc_Unarc      equ 0021448h
_DelVarArc      equ 0021434h

_SetParserHook      equ 002149Ch
_SetAppChangeHook   equ 00214A4h
_ClrParserHook      equ 00214A0h
_ClrAppChangeHook   equ 00214A8h
